# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_URL=http://localhost:8080
    volumes:
      - ./logs:/app/logs
    networks:
      - crawler-network
    # Ensure logs directory exists
    command: >
      sh -c "
        mkdir -p /app/logs &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - crawler-network

networks:
  crawler-network:
    driver: bridge
